export const SCREEN_NAMES = {
  WELCOME: 'Welcome',
  MAIN: 'Main',
  ON_BOARDING: 'OnBoarding',
  BOOK_DEMO_FORM: 'BookDemoForm',
  BOOK_DEMO_SLOTS: 'BookDemoSlots',
  COURSE_DETAILS: 'CourseDetails',
  PAYMENT: 'Payment',
  BATCH_FEE_DETAILS: 'BatchFeeDetails',
  SIGNUP: 'Signup',
  EMAIL_LOGIN: 'EmailLogin',
  VERIFY_CODE: 'VerifyCode',
  USER_COURSES_PAGE: 'UserCoursePage',
  COURSE_LEVEL_PAGE: 'CourseLevelPage',
  COURSE_CONDUCT_PAGE: 'CourseConductScreen',
  PAYMENT_SUCCESS: 'paymentSuccess',
  REFERRAL: 'referral',
  MYTICKETS: 'myTicket',
  PHONELOGIN: 'phonelogin',
};
